# Generated by Django 2.2.3 on 2019-07-07 03:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pipe.validators.pipe.events_validators
import pipe.validators.pipe.tickets_validators


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0002_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(validators=[pipe.validators.pipe.events_validators.validate_id, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[pipe.validators.pipe.events_validators.validate_startdate], verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipe.Event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_cost',
            field=models.FloatField(validators=[pipe.validators.pipe.tickets_validators.validate_cost]),
        ),
    ]
